### ISSUE TITLE
I have error code on dart DioError [DioErrorType.response]: Http status error [404]

### ISSUE THREAD

**Issue by arai77** [TechnoLX/Flutter-Doctor-Appointment-App-With-Laravel#1]
Hello..
Mr. TechnoLX..
I like your code and project.. But I have problem when I try to use register form in mobile emulator. But when I try on postman with your code laravel, it's work normal.. Respone from when debugprint after klik sign up is  show error is DioError [DioErrorType.response]: Http status error [404].. Could you help me

**Comment by arai77** [comment]
I have another problem to when I try to login its show error E/flutter ( 3287): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'DioError' is not a subtype of type 'bool'.. Could you help me plese..

**Comment by TechnoLX** [comment]
Hi, regarding your first question, is indicating might have some issues on your api setting / api routing issue, please double check your api, and make sure everything is correct on your local. 
secondly, i am not quite sure what issue about second question, however, you may check your authentication when login, see if the token is correct.
